services:
  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - "8081:8081"  # Port du backend
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - ada

  frontend:
    image: frontend
    build:
      context: ./ada-platform
    ports:
      - "8080:8080"  # Port du frontend
    depends_on:
      - backend
    networks:
      - ada

  database:
    image: mysql:latest
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: ada_db
    ports:
      - "3306:3306"  # Port de la base de données
    networks:
      - ada

networks:
  ada:
    driver: bridge

volumes:
  db-data: